version: '3.8'

services:
  postgresql:
    image: postgres:17.5
    container_name: lista-db
    environment:
      POSTGRES_DB: lista_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - lista-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build: .
    container_name: lista-app
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/lista_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
    ports:
      - "8080:8080"
    networks:
      - lista-network
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  lista-network:
    driver: bridge